version: '3'

services:
  hhgw:
    build: .
    labels:
      - traefik.enable=true
      - traefik.http.routers.hhgw-router.rule=Host(`${ROUTER_HOST}`) || Host(`hhgw.loc`)
      - traefik.http.routers.hhgw-router.service=hhgw-service
      - traefik.http.services.hhgw-service.loadbalancer.server.port=8080
    environment:
      - hhg.icinga.accept_url_regex=.*
      - hhg.icinga.proxy_host=https://some-icinga.com
      - hhg.icinga.proxy_path=/hooks/12345
      - hhg.icinga.request_file=/tmp/icinga.request
    networks: [ traefik-network ]
networks:
  traefik-network:
    external: true